version: '2'

services:
  jupyterlab:
    # container_name: course-xgboost
    container_name: jupyterlab_container
    build: ./jupyterlab
    working_dir: /notebooks
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/notebooks